### ISSUE TITLE
How to export the painting to image

### ISSUE THREAD

**Issue by blue492** [timcreatedit/scribble#1]
Hi, 
Is it possible to export the painting/drawing I did in scribble to image (jpg, png) or pdf ?

Best regards
Mike

**Comment by timcreatedit** [comment]
Hi,
at the moment, this is not possible. It is a planned feature however and should arrive in the near future :)

**Comment by timcreatedit** [comment]
Version 0.2.0 is out and with it comes a renderImage() method in the ScribbleNotifier! You can take a look at the example to see how it works :) feel free to contact me if you have any more questions
