### ISSUE TITLE
Can you stream the drawing in real-time like whiteboardkit

### ISSUE THREAD

**Issue by Ayush412** [timcreatedit/scribble#2]
[whiteboardkit](https://pub.dev/packages/whiteboardkit#stream-eg-online-whiteboard) has the ability to stream the drawing to other users via json. Any plans on having a similar feature in future updates?

**Comment by timcreatedit** [comment]
Hi :)
there is no need to implement this, as you can do it yourself pretty easily already and such functionality would only clutter the package.

If you want to implement it, just listen to the ``ScribbleNotifier`` using ``addListener()`` to receive realtime updates of it's state. You can then convert this state to json and send it somewhere if you like (e.g. over firebase)

**Comment by jtkeyva** [comment]
Any chance of an example that includes this? Like perhaps a view with 2 panels. One that you draw on and the other mimicking it?
