### ISSUE TITLE
How to switch back to drawing mode from eraser mode?

### ISSUE THREAD

**Issue by jack-szeto** [timcreatedit/scribble#37]
Hello,

I'm using the Scribble package in my Flutter project and I've successfully implemented the eraser mode using the `setEraser` function in the `ScribbleNotifier`. However, I'm unsure how to switch back to the drawing mode once I'm in the eraser mode. 

Is there a specific method or a recommended way to toggle between these modes? Any guidance would be greatly appreciated.

Thank you!

**Comment by timcreatedit** [comment]
Hi, the eraser is basically treated like a color, so just call `setColor` and it will go back to drawing with that color :)
