### ISSUE TITLE
Undo Redo Issue with loading scribble from json

### ISSUE THREAD

**Issue by Sesa1988** [timcreatedit/scribble#40]
Hi, its a great package but I have some issues with the Undo Redo feature when loading from json:

- Redo deletes the whole painting (can redo is also true before executing the action). 
- If I play around with some methods like clearQueue() and set the flag addToUndoHistory to false, it odes not recognise the first line but at least does not remove the whole painting (can redo is also false in this case). Undo does also not work on the first erase on the second case, something seems weird.

In either case I can't make it properly work. Im using flutter_bloc for state and and tried a dirty hack to get the state from the notifier every 100 milliseconds to make sure its not an issue on my side, the behaviour is one of the above described.

**Comment by Sesa1988** [comment]
> Hi,
> 
> I have an issue that the redo deletes the whole painting (can redo is also true) or if I play around with some methods like clearQueue and addToUndoHistory false etc. it does not recognise the first line but at least does not remove the whole painting (can redo is also false).
> 
> In either case I can't make it properly work. Im using flutter_bloc for state and even did a dirty hack to update the state every 100 milliseconds to test it but it seems like a bug in the library from my point of view.

**Comment by timcreatedit** [comment]
Hey @Sesa1988! 

Could you share a few more details about how you are loading the sketch from json? I've added a few tests to verify the behavior in #69, and everything seems to behave correctly. Maybe you could take a look and compare it to what you're doing and why it might be different?

**Comment by timcreatedit** [comment]
I'm gonna go ahead and close this due to inactivity. If you have anymore questions, just respond to this and @ me, I'll reopen it :)
