### ISSUE TITLE
Do I have any possibility to set a sketch if I have a Uint8List image?

### ISSUE THREAD

**Issue by iak-a-dev** [timcreatedit/scribble#59]
Is it possible to set a sketch using a Uint8List image?

**Comment by timcreatedit** [comment]
Hi, are you looking for the possibility to set a background image? Or do you want to "open" a sketch from an image? The second case is not possible, and will most probably never be supported as it would require "detecting" lines, which is complicated and outside of the scope of this package.

**Comment by iak-a-dev** [comment]
Yes, my question was related to the second option. Thanks for your answer.
