### ISSUE TITLE
Support for panning and infinite canvas

### ISSUE THREAD

**Issue by shujaatak** [timcreatedit/scribble#7]
Can you please add support for panning canvas and infinite size of it?

**Comment by timcreatedit** [comment]
Panning can easily be achieved using the InteractiveViewer Widget and is not in the scope of this package as it’s designed to be as simple and therefore as customizable as possible. For the same reason I don’t plan on implement infinite canvas, you could experiment with a super large scribble widget in an InteractiveViewer
