### ISSUE TITLE
Change Previous Color on Background Color Change

### ISSUE THREAD

**Issue by Nightbl927** [timcreatedit/scribble#9]
Hi,

I've been trying to solve a problem but can't find the best way to do so.  If I was drawing in black and then changed the background color to black, what would be the best way to change the previous lines that were black to white?  The only thing I could think of was iterate through the JSON, find all of the instances that have the black color assignment and change it manually to a white color.

Even this process, I am having trouble iterating through the JSON.  Unfortunately, I am a newbie to Dart.

**Comment by timcreatedit** [comment]
I'd recommend using something like 
```dart
state = state.copyWith.sketch(
    lines: state.sketch.lines.map((l) => l.color == 0xFF000000 ? l.copyWith(color: 0xFFFFFFFF) : l).toList(),
);
```

**Comment by Nightbl927** [comment]
Awesome, thanks for the tip!
